<?php $columns = $this->getColumns(); ?>
<table class="data-table" id="stockreminder-table">
    <?php if (count($this->getStockItems())): ?>
    <thead>
        <tr class="first last">
            <th></th>
            <th><?php echo $this->__('Product Details') ?></th>
            <th><?php echo $this->__('Add to Cart') ?></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->getStockItems() as $item): ?>
            <?php $product = Mage::getModel('catalog/product')->load($item->getProductId());
                  $stocklevel = (int)Mage::getModel('cataloginventory/stock_item')
                                    ->loadByProduct($product)->getQty();

                //Bundle Check
                if ($product->getTypeId() == Mage_Catalog_Model_Product_Type::TYPE_BUNDLE) {
                    $bundled_product = new Mage_Catalog_Model_Product();
                    $bundled_product->load($product->getId());

                    $selectionCollection = $bundled_product->getTypeInstance(true)->getSelectionsCollection(
                    $bundled_product->getTypeInstance(true)->getOptionsIds($bundled_product), $bundled_product
                    );

                    foreach ($selectionCollection as $option) {
                        $bundleItemStock = Mage::getModel('cataloginventory/stock_item')->loadByProduct($option->product_id);
                        $bundleStockArray[] = $bundleItemStock->getQty();
                    }
                    $stocklevel = min($bundleStockArray);
                }

                //Url verification
                $url     = $product->getProductUrl();
                $rewrite = Mage::getModel('core/url_rewrite');

                $arrayOfParentIds = Mage::getSingleton('catalog/product_type_configurable')->getParentIdsByChild($product->getId());
                if ($arrayOfParentIds) {
                    $rewrite->loadByIdPath('product/'.$arrayOfParentIds[0]);
                    $url = Mage::getUrl($rewrite->getRequestPath(), ['_current' => false]);

                    if ($product->getTypeId() == Mage_Catalog_Model_Product_Type::TYPE_SIMPLE) {
                        $productSimple = Mage::getModel('catalog/product')->load($arrayOfParentIds[0]);
                        $url = Mage::getUrl($productSimple->getUrlPath(), ['_current' => false]);
                    }
                }
            ?>
            <tr id="item_<?php echo $item->getStockreminderId();?>">
                <td><a class="product-image" href="<?php echo $url ?>" title="<?php  echo $this->escapeHtml($product->getName()); ?>">
                        <img src="<?php echo $this->helper('catalog/image')->init($product, 'small_image')->resize(113, 113); ?>" width="113" height="113" alt="<?php echo $this->escapeHtml($product->getName()) ?>" />
                    </a>
                </td>
                <td><h3 class="product-name">
                    <a href="<?php echo $url ?>" title="<?php  echo $this->escapeHtml($product->getName()); ?>">
                        <?php  echo $this->escapeHtml($product->getName()); ?></a>
                    </h3>
                    <div class="description std">
                        <div class="inner"><?php echo $product->getShortDescription(); ?></div>
                    </div>
                </td>
                <td>
                    <div class="cart-cell">
                        <?php
                        if ($product->isSaleable() && $stocklevel >= $item->getQty()): ?>
                            <form action="<?php echo Mage::helper('checkout/cart')->getAddUrl($product); ?>" method="post">
                                <?php echo $this->getPriceHtml($product);?>
                                <div class="add-to-cart-alt">
                                    <input type="text" class="input-text qty validate-not-negative-number" name="qty" value="<?php echo $item->getQty()*1 ; ?>">
                                    <input type="hidden" name="product" value="<?php echo $product->getId() ?>">
                                    <button type="submit" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                            </form>
                        <?php else: ?>
                            <p class="availability out-of-stock"><span><?php echo $this->__('Waiting for stock') ?></span></p>
                        <?php endif; ?>
                        </div>
                    </div>
                </td>
                <td class="last">
                    <a href="<?php echo $this->getUrl('*/*/remove/', array('id' => $item->getStockreminderId())) ?>"
                    title="<?php echo $this->__('Remove Item') ?>"
                    class="out-of-stock"><span><span><?php echo $this->__('Remove item');?></span></span></a>
                </td>
            </tr>
        <?php endforeach ?>
        <?php else: ?>
            <td colspan="<?php echo count($columns);?>" class="stockreminder-empty"><?php echo $this->__('This Stock Reminder has no products');?></td>
        <?php endif; ?>
    </tbody>
</table>