<div class="my-stockreminder">
    <div class="page-title title-buttons">
        <h1><?php echo $this->getTitle(); ?></h1>
    </div>
    <?php echo $this->getMessagesBlock()->toHtml(); ?>

        <?php echo $this->getChildHtml('top'); ?>
        <fieldset>
            <?php
            if ($this->hasStockreminderItems()): ?>
                <?php echo $this->getBlockHtml('formkey');?>
                <?php $this->getChild('items')->setItems($this->getStockreminderItems()); ?>
                <?php echo $this->getChildHtml('items');?>
                <script type="text/javascript">decorateTable('stockreminder-table')</script>
            <?php else: ?>
                <p class="stockreminder-empty"><?php echo $this->__('You have no items in your Stock Reminder.') ?></p>
            <?php endif ?>
        </fieldset>
</div>
<?php echo $this->getChildHtml('bottom'); ?>
<div class="buttons-set">
    <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
</div>
